### ISSUE TITLE
Feature Request: better mouse controls (zoom and panning)

### ISSUE THREAD

**Issue by SaphireLattice** [logisim-evolution/logisim-evolution#1262]
It would be really nice to have zoom on scroll wheel (instead of scrolling through the Y direction), and a drag-to-pan operation on the middle mouse press.

I hacked in the former for myself locally and it improved my experience with this drastically, but sadly I can't really manage to understand the rabbit hole that is tool and input handling :P

Though, the scroll wheel thing might need to have an option for that, given that it is currently used for, well, scrolling the canvas in Y direction.

**Comment by maehne** [comment]
Thanks for the suggestion @SaphireLattice!

Zooming with scroll wheel already works if you hold down `Ctrl` key. Certain mice have scroll wheels for both x and y direction. Therefore, I am not in favour for this suggested change.

However, I am less opposed against the proposed pan feature. We may consider whether implementing it similarly to the zoom by holding down a modifier key would be more intuitive.

**Comment by SaphireLattice** [comment]
Thanks for the reply as well!

That's nice to know, though it still runs into the same problem I have with current system is that I basically have to keep using keyboard constantly alongside the mouse. Holding `Ctrl` key is a lot less annoying than arrow keys, though, for sure, as it only needs the other hand. And oh, forgot that X-axis scrolling is an actual thing. Everything I have seen with that hasn't *actually* worked. Hence my confusion as to why it was implemented such.

I wonder if this could be implemented as a settings option? Especially if panning gets added as a holding-a-key-only thing. Just a toggle between whether `Ctrl` turns from scrollwheel-nav to zoom & pan, and vice-versa.

And on the mouse being used for panning itself, holding middle mouse button to pan would be nice. Though this probably should be an option too, between other mouse buttons, if there's a way in UI to rebind a key. Not sure if I missed one?

**Comment by maehne** [comment]
Actually, panning with the mouse is already possible by holding down the *left* mouse button when the "hand tool" 
<img width="26" alt="grafik" src="https://user-images.githubusercontent.com/1174243/140897285-73e8b7c0-2f09-4a3f-b3a9-338d506f2eeb.png"> (`Ctrl`+`1`) is active.

I noticed that zooming with the mouse wheel while holding down the `Ctrl` key could be improved. It is using the global origin for zooming instead of the point where is currently located the mouse. Thus, you are always forced to reposition the shematic after a zoom operation, which is kind of annoying. Also, on macOS, probably holding down `CMD` should also enable zoom with scroll wheel to match behaviour with other apps (e.g., Firefox).

Mapping pan globally to the middle mouse button should be doable as well as adding a configuration option whether the scrollwheel should be used for panning or zooming. For the moment, this does not have high priority for us, but we welcome any PR implementing this functionality.

**Comment by goofyseeker311** [comment]
there is an additional pan viewpoint jumping issue with panning using middle mouse button in v.4.1.0.
sometimes the pan focus jumps fast to very far from the location even if mouse was not moved that much or at all.

edit: double clicking middle mouse button seems to reset to center. that happens too easily, and should not happen by the middle mouse button. the two actions are too close to each other, because middle button dragging can easily become a double click.

**Comment by maehne** [comment]
@goofyseeker311: Please check with our [Nightly builds](https://github.com/logisim-evolution/logisim-evolution#:~:text=Nightly-,builds,-We%20also%20offer) whether this is still the case, as there have been many bug fixes merged over the past weeks.

**Comment by goofyseeker311** [comment]
yes, in the recent nightly, double clicking middle mouse button still centers the view. it should be removed completely or be able to change the key binding to something else.

edit: changing windows double click speed settings to very long seems to have partially solved the issue.

**Comment by goofyseeker311** [comment]
one additional issue with mouse behaviour, if you add/drag a wire or a component, with left mouse button, then press right mouse button while still pressing dragging the left mouse button, the operation is cancelled. also this behaviour should be removed or be remapped to another hot-key. reasoning is that default undo action should be ctrl-z not the mouse two-button press. also middle + right mouse button sets the tool to hand, also should not be happening. interrupts the main mouse button actions too easily.

all of the mentioned issues are kinda very annoying when doing work in logisim very often.

edit: why are the mouse button key settings in the project settings not in general settings? also when dragging components with shift, not computing connections, one of the to-be-dragged components gets de-selected.

edit: side note, when moving components around, in a large circuit, every connection gets recalculated, not only the ones that changed. makes editing very slow in very large circuits.
