### ISSUE TITLE
Undo/Redo not working while editing text labels / Undo manager registers editing of text without change

### ISSUE THREAD

**Issue by Rudrajiii** [logisim-evolution/logisim-evolution#2097]
https://github.com/user-attachments/assets/251ee722-c1f7-40d8-a686-5c6b3b7c3f82

Here i am trying to select the text under that text-box but unable to do that 
so it would be great if i able to select that text to either to edit or delete the text in single move.
also right now the `CTRL + Z` , `CTRL + C` , `CTRL + V` is not working !!
would be beneficial if i able to do that so that i can easily copy and paste the and undo my changes in the text box itself.
@klenin @btb  @chuckb @MosheBerman please look into this.

**Comment by davidhutchens** [comment]
Thank you for the report. I can replicate this on v3.9.0 and on the head of the main branch.

When you select the Text object, there is an attribute in Properties labeled Text. It contains the string. You can select portions of the text and use copy and paste to edit the string there. So your main requested functionality is actually available.

As for undo and redo, the actual update doesn't happen until you finish editing. So our undo manager sees a single change. Undo will then return you to the original value and redo back to the new one. Therefore, undo/redo will not work within the editing process.

It would be nice, and more intuitive, if editing the object in place would allow selection, copy, and paste. I recommend leaving this issue open.

I also noticed in checking this issue that the undo manager registers an action if the text is opened for editing and closed without change. In that case undo does nothing observable and the user may be left wondering if undo works. It would be better if no undo action is registered in that case.

**Comment by maehne** [comment]
Thanks @davidhutchens for your analysis of the issue! I agree with your conclusions regarding how Logisim-evolution should behave.

PRs in this direction are welcome!

**Comment by maehne** [comment]
@Rudrajiii: I have adjusted the title of this issue to reflect the analysis of @davidhutchens.

**Comment by hewzhew** [comment]
I rechecked this against current `main`.

The no-op undo part has already been addressed by #2585: opening a text label for editing and closing it unchanged no longer creates a commit action.

I also exercised the current `TextFieldCaret` behavior directly. At the caret level, in-place text editing now supports:

- mouse drag selection,
- `Ctrl+A`,
- `Ctrl+C` / `Ctrl+X`,
- `Ctrl+V` replacing the selected text.

So the original selection/copy/paste part appears to be implemented in current HEAD. The remaining undo/redo behavior while an edit is still in progress seems to match the earlier analysis: the project undo stack sees one committed text edit after editing is finished, not intermediate edits inside the active text caret.

Would it make sense to close this issue, or narrow it to only the in-progress undo/redo behavior if maintainers still want that changed?

**Comment by maehne** [comment]
@davidhutchens: Could you please comment on @hewzhew's assessment?

I did a quick test and noticed an inconsistency in behaviour on macOS. While editing a text label, cut, copy, and paste only work using the Windows/Linux-specific key shortcuts Ctrl+x, Ctrl+c, Ctrl+v instead of macOS variants CMD+x, CMD+y, CMD+v. Also, UNDO isn't working while editing the text label. This is inconstant and should be addressed.

I therefore suggest to keep this issue open. PRs to address this inconsistency are very welcome!

**Comment by davidhutchens** [comment]
I agree with @maehne that the cmd-x, cmd-c, cmd-v shortcuts do not work in macOS. I also note that the Edit menu items for these are disabled.

The program is not registering editing changes to the Undo Manager while editing text, so we cannot undo the edits. This is how it worked before.

When we finish editing, it does register a undo item. But that undo item does not do anything so it doesn't return to the original text. This looks like a regression as I noted above that it did work.

**Comment by maehne** [comment]
Thanks for the feedback @davidhutchens!

**Comment by hewzhew** [comment]
Following up on the earlier discussion, I rechecked #2097 against current `main`. The remaining behaviors now appear to be covered by the merged PRs:

- #2585 avoids creating undo actions for unchanged text edits.
- #2698 adds platform-appropriate text-editing shortcuts, in-progress undo/redo, and restores project-level undo after the edit is committed.
- #2707 routes the Edit menu actions, including Undo/Redo, to the active text caret and restores normal project handling after editing ends.

The focused `TextFieldCaretTest`, `TextToolTest`, and `InstanceTextFieldTest` suites also pass on current `main`. Since #2707 was manually reviewed with the Edit menu working as expected, I believe the behaviors tracked here are now addressed. Would it make sense to close this issue?

**Comment by maehne** [comment]
I agree and close this issue as resolved. @Rudrajiii: Please reopen if problems persist in the current Nightly builds.
